const translations = {
    en: {
        'lng-logo': 'Attorneyster',
        'lng-login': 'Go to login',
        'lng-book': 'Book A Consultation',
        'lng-home': 'Home',
        'lng-about': 'About Us',
        'lng-pages': 'Pages',
        'lng-contact': 'Contact Us',
        'lng-call': 'Call Us On',
        'lng-mail': 'Email Us On:',
        'lng-were': "We're Group of Certified law Professionals",
        'lng-wehave': "We have helped countless maritime workers and their families go up against the largest offshore companies and win",
        'lng-getin': 'Get in Touch',
        'lng-corporate': 'Corporate Law',
        'lng-friday': 'Friday, February 4, 2022',
        'lng-empowering': 'Empowering Innovation Through Blockchain Technology',
        'lng-weare1': 'We are a leading blockchain development company, dedicated to creating innovative solutions that revolutionize industries and empower businesses worldwide.',
        'lng-learn': 'Learn More',
        'lng-additional': 'Additional Information',
        'lng-here': 'Here you can find more details about our blockchain technology and how it can benefit your business. Our team of experts is dedicated to providing cutting-edge solutions tailored to your specific needs.',
        'lng-attorneyster': 'Attorneyster',
        'lng-quick': 'Quick Link',
        'lng-home1': 'Home',
        'lng-about1': 'About Us',
        'lng-pricing': 'Pricing',
        'lng-test': 'Testimonial',
        'lng-contact3': 'Contact Us',
        'lng-utility': 'Utility Pages',
        'lng-style': 'Style Guide',
        'lng-licenses': 'Licenses',
        'lng-protected': 'Protected',
        'lng-change': 'Changelog',
        'lng-error': 'Error Page',
        'lng-practice': 'Practice Area',
        'lng-business2': 'Business Law',
        'lng-construction1': 'Construction Law',
        'lng-car1': 'Car Accident',
        'lng-criminal3': 'Criminal Law',
        'lng-family1': 'Family Law',
        'lng-attorney': 'Attorney Law Office, 121 King Street, <br> 90027, USA.',
        'lng-phone1': 'Phone: (011) 9876 54321',
        'lng-mail2': 'Email: Info@Example.Com',
        'lng-copy': 'Copyright © Attorney Law | Designed by ',
        'lng-victor': 'VictorFlow',
        'lng-web': 'Webflow',
        'lng-folow': 'Follow :'
    },
    ru: {
        'lng-logo': 'Адвокат',
        'lng-login': 'Войти',
        'lng-book': 'Записаться на консультацию',
        'lng-home': 'Главная',
        'lng-about': 'О нас',
        'lng-pages': 'Страницы',
        'lng-contact': 'Контакты',
        'lng-call': 'Позвоните нам',
        'lng-mail': 'Напишите нам:',
        'lng-were': 'Мы группа сертифицированных юристов',
        'lng-wehave': 'Мы помогли бесчисленным морским рабочим и их семьям противостоять крупнейшим оффшорным компаниям и победить',
        'lng-getin': 'Свяжитесь с нами',
        'lng-corporate': 'Корпоративное право',
        'lng-friday': 'Пятница, 4 февраля 2022',
        'lng-empowering': 'Раскрытие инноваций через блокчейн-технологии',
        'lng-weare1': 'Мы ведущая компания по разработке блокчейн, посвященная созданию инновационных решений, которые революционизируют отрасли и дают возможность бизнесу по всему миру.',
        'lng-learn': 'Узнать больше',
        'lng-additional': 'Дополнительная информация',
        'lng-here': 'Здесь вы можете найти больше деталей о наших блокчейн-технологиях и о том, как они могут принести пользу вашему бизнесу. Наша команда экспертов стремится к предоставлению передовых решений, адаптированных к вашим специфическим потребностям.',
        'lng-attorneyster': 'Адвокат',
        'lng-quick': 'Быстрая ссылка',
        'lng-home1': 'Главная',
        'lng-about1': 'О нас',
        'lng-pricing': 'Цены',
        'lng-test': 'Отзывы',
        'lng-contact3': 'Контакты',
        'lng-utility': 'Полезные страницы',
        'lng-style': 'Справочник по стилю',
        'lng-licenses': 'Лицензии',
        'lng-protected': 'Защита',
        'lng-change': 'Изменения',
        'lng-error': 'Страница ошибки',
        'lng-practice': 'Практика',
        'lng-business2': 'Бизнес право',
        'lng-construction1': 'Строительное право',
        'lng-car1': 'Автомобильные аварии',
        'lng-criminal3': 'Уголовное право',
        'lng-family1': 'Семейное право',
        'lng-attorney': 'Адвокатское бюро, 121 Кинг Стрит, <br> 90027, США.',
        'lng-phone1': 'Телефон: (011) 9876 54321',
        'lng-mail2': 'Эл. почта: Info@Example.Com',
        'lng-copy': 'Авторские права © Адвокат | Разработано ',
        'lng-victor': 'ВикторФлоу',
        'lng-web': 'Вебфлоу',
        'lng-folow': 'Следуйте :'
    }
};

document.getElementById('languageSwitcher').addEventListener('change', function () {
    const selectedLang = this.value;
    document.querySelectorAll('[data-class]').forEach(element => {
        const key = element.getAttribute('data-class');
        element.innerHTML = translations[selectedLang][key];
    });
});